package cod;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author P3DR0
 */
public class Reproducir extends javax.swing.JPanel {

    /**
     * Creates new form Reproducir
     */
    
    Reproductor reproductor;
    
    public Reproducir() {
        initComponents();
        reproductor = new Reproductor();
    }

    public void Reproduce(){
        String ruta = "C:\\Users\\P3DR0\\Videos\\videoplayback.mp4";
            if (!ruta.isEmpty()) {                                    
                
                this.reproductor.setRuta(ruta);
                this.reproductor.setJpanel(this);
                this.setVisible(true);
                this.reproductor.mostrarVideo();
                this.reproductor.reproducir();
    }
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
