
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 12 23:50:11 MDT 2025
//----------------------------------------------------

package cod;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 18;
  public static final int Coma = 36;
  public static final int Metodo = 7;
  public static final int Llave_c = 25;
  public static final int Op_booleano = 21;
  public static final int Puente = 3;
  public static final int Llave_a = 24;
  public static final int Mario = 4;
  public static final int NumeroFlotante = 32;
  public static final int PowerUp = 11;
  public static final int Castillo = 9;
  public static final int Corchete_c = 27;
  public static final int Corchete_a = 26;
  public static final int Luigi = 5;
  public static final int Division = 16;
  public static final int Cadena = 34;
  public static final int Parentesis_c = 23;
  public static final int Parentesis_a = 22;
  public static final int EOF = 0;
  public static final int P_coma = 29;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 19;
  public static final int ERROR = 35;
  public static final int Op_logico = 17;
  public static final int Chomp = 6;
  public static final int Tuberia = 31;
  public static final int Identificador = 30;
  public static final int Resta = 14;
  public static final int Multiplicacion = 15;
  public static final int Op_incremento = 20;
  public static final int Toad = 8;
  public static final int Numero = 33;
  public static final int Peach = 10;
  public static final int Suma = 13;
  public static final int Main = 28;
  public static final int Igual = 12;
}

