package cod;

public enum Tokens{
    Linea,
    T_dato,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Op_logico,
    Op_incremento,
    Op_relacional,
    Op_atribucion,
    Op_booleano,
    Parentesis_a,
    Parentesis_c,
    Llave_a,
    Llave_c,
    Corchete_a,
    Corchete_c,
    Main,
    P_coma,
    Identificador,
    Numero,
    ERROR,
    Mario,
    Luigi,
    Tuberia,
    Puente,
    Chomp,
    NumInvalido,
    IdentificadorInvalido,
    Mover,
    Metodo   ,
    Peach,
    Castillo,
    Toad,
    Mushroom,
    Ffuego,
    Tanuki,
    Frog,
    Capa
}
